defaults:
  - rl_config_base


# Model arguments
model_name_or_path: Qwen/Qwen2.5-1.5B

# Data training arguments
dataset_name: xiaodongguaAIGC/X-R1-750
dataset_configs:
- train

# GRPO trainer config
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.5
do_eval: false
eval_strategy: "no"
eval_steps: 10
gradient_accumulation_steps: 4
learning_rate: 3.0e-06
log_level: info
logging_steps: 10
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 256
num_generations: 6
max_completion_length: 1024
max_steps: -1
num_train_epochs: 3
output_dir: output/X-R1-3B
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 4
push_to_hub: false
report_to:
- wandb
save_strategy: "epoch"
seed: 42
warmup_ratio: 0.1