from setuptools import setup, find_packages
import shutil
from pathlib import Path

# Remove stale tinyzero_trl-info directory to avoid https://github.com/pypa/pip/issues/5466
stale_egg_info = Path(__file__).parent / "tinyzero_trl-info"
if stale_egg_info.exists():
    print(
        (
            "Warning: {} exists.\n\n"
            "If you recently updated open_r1, this is expected,\n"
            "but it may prevent open_r1 from installing in editable mode.\n\n"
            "This directory is automatically generated by Python's packaging tools.\n"
            "I will remove it now.\n\n"
            "See https://github.com/pypa/pip/issues/5466 for details.\n"
        ).format(stale_egg_info)
    )
    shutil.rmtree(stale_egg_info)



install_requires = [
    "numpy",
    "torch"
]

extras = {}
extras["dev"] = [
    "black",      
    "flake8",    
    "pytest" 
]


setup(
    name="tinyzero_trl",
    version="0.1.0",
    packages=find_packages(exclude=["tests", "tests.*"]),
    author="Maojia and the Hugging Face team (past and future)",
    description="Easy-to-use framework for reproducing R1-Zero",
    license="Apache",
    url="https://github.com/MAOJIASONG/TinyZero-TRL",
    package_dir={"": "src"},
    zip_safe=False,
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Intended Audience :: Education",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    install_requires=install_requires,
    extras_require=extras,
    python_requires=">=3.10.9",
)
