# @package _global_
defaults:
  - grpo-qwen-2.5-3b-base

exp_name: grpo_qwen2.5-3b_inst


# Model arguments
model_name_or_path: Qwen/Qwen2.5-3B-Instruct

# GRPO trainer config
output_dir: outputs/countdown_qwen2.5-3b_inst
overwrite_output_dir: true
max_steps: 450
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-7 # 1.0e-6 as in the deepseek math paper 5-e7 from https://hijkzzz.notion.site/unraveling-rlhf-and-its-variants-engineering-insights#147d9a33ecc9806090f3d5c749d31f05
# GRPO specific parameters
beta: 0.001 # 0.04 as in the deepseek math paper 0.001 from https://hijkzzz.notion.site/unraveling-rlhf-and-its-variants-engineering-insights#147d9a33ecc9806090f3d5c749d31f05
max_prompt_length: 256
max_completion_length: 1024
num_generations: 8
temperature: 0.9
use_vllm: true
vllm_device: "cuda:3"
vllm_gpu_memory_utilization: 0.9

# Logging arguments
logging_steps: 2
report_to:
  - tensorboard
save_strategy: "no"
save_steps: 25
# wandb_entity: grpo
# wandb_project: countdown-grpo-qwen2.5-3b-base

# Hugging Face Hub 
push_to_hub: false
hub_model_id: qwen2.5-3b_inst-countdown-grpo # if not defined same as output_dir
hub_strategy: every_save