# @package _global_
exp_name: grpo_qwen2.5-3b_base


# Model arguments
model_name_or_path: models/Qwen2.5-3B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Lora Arguments
# No LoRA is used here

# Data training arguments
dataset_mixer:
  Jiayi-Pan/Countdown-Tasks-3to4: 0.1
dataset_splits:
  - train
dataset_configs:
  - default
system_prompt: "You are a helpful assistant. You first thinks about the reasoning process in the mind and then provides the user with the answer."
truncation_side: left
preprocessing_num_workers: 10

# GRPO trainer config
output_dir: outputs/countdown_qwen2.5-3b_base
overwrite_output_dir: true
bf16: true
max_steps: 450
per_device_train_batch_size: 8
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-7 # 1.0e-6 as in the deepseek math paper 5-e7 from https://hijkzzz.notion.site/unraveling-rlhf-and-its-variants-engineering-insights#147d9a33ecc9806090f3d5c749d31f05
lr_scheduler_type: cosine
warmup_ratio: 0.03
# GRPO specific parameters
beta: 0.001 # 0.04 as in the deepseek math paper 0.001 from https://hijkzzz.notion.site/unraveling-rlhf-and-its-variants-engineering-insights#147d9a33ecc9806090f3d5c749d31f05
max_prompt_length: 256
max_completion_length: 1024
num_generations: 8
temperature: 0.9
use_vllm: true
# vllm_device: "cuda:3"
vllm_gpu_memory_utilization: 0.6
reward_funcs:
  - countdown_format
  - countdown_equation
reward_weights:
  - 1.0
  - 1.0

# Logging arguments
log_level: info
logging_first_step: true
log_completions: true
logging_strategy: steps
logging_steps: 2
report_to:
  - tensorboard
save_strategy: "no"
save_steps: 25
seed: 42
# wandb_entity: grpo
# wandb_project: countdown-grpo-qwen2.5-3b-base

# Hugging Face Hub 
push_to_hub: false
hub_model_id: qwen2.5-3b_base-countdown-grpo # if not defined same as output_dir
hub_strategy: every_save

